# Generated by Django 4.1.7 on 2023-03-25 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[
                 django.core.validators.MaxValueValidator(60)])),
                ('gender', models.CharField(choices=[
                 ('M', 'M'), ('F', 'F'), ('T', 'T')], max_length=1)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
